-- MySQL Script generated by MySQL Workbench
-- 10/14/17 00:19:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema futbolito
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema futbolito
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `futbolito` DEFAULT CHARACTER SET utf8 ;
USE `futbolito` ;

-- -----------------------------------------------------
-- Table `futbolito`.`Rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `futbolito`.`Rol` ;

CREATE TABLE IF NOT EXISTS `futbolito`.`Rol` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futbolito`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `futbolito`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `futbolito`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  `Contrasena` VARCHAR(45) NULL,
  `idRol` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Rol1_idx` (`idRol` ASC),
  CONSTRAINT `fk_Usuario_Rol1`
    FOREIGN KEY (`idRol`)
    REFERENCES `futbolito`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futbolito`.`Recinto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `futbolito`.`Recinto` ;

CREATE TABLE IF NOT EXISTS `futbolito`.`Recinto` (
  `idRecinto` INT NOT NULL AUTO_INCREMENT,
  `Direccion` VARCHAR(45) NULL,
  `Horario` VARCHAR(45) NULL,
  PRIMARY KEY (`idRecinto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futbolito`.`Cancha`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `futbolito`.`Cancha` ;

CREATE TABLE IF NOT EXISTS `futbolito`.`Cancha` (
  `idCancha` INT NOT NULL AUTO_INCREMENT,
  `Numero` INT NULL,
  `Estado` VARCHAR(45) NULL,
  `idRecinto` INT NOT NULL,
  PRIMARY KEY (`idCancha`, `idRecinto`),
  INDEX `fk_Cancha_Recinto1_idx` (`idRecinto` ASC),
  CONSTRAINT `fk_Cancha_Recinto1`
    FOREIGN KEY (`idRecinto`)
    REFERENCES `futbolito`.`Recinto` (`idRecinto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futbolito`.`Reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `futbolito`.`Reserva` ;

CREATE TABLE IF NOT EXISTS `futbolito`.`Reserva` (
  `Usuario_idUsuario` INT NOT NULL,
  `Cancha_idCancha` INT NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `Cancha_idCancha`),
  INDEX `fk_Usuario_has_Cancha_Cancha1_idx` (`Cancha_idCancha` ASC),
  INDEX `fk_Usuario_has_Cancha_Usuario_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Usuario_has_Cancha_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `futbolito`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Cancha_Cancha1`
    FOREIGN KEY (`Cancha_idCancha`)
    REFERENCES `futbolito`.`Cancha` (`idCancha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futbolito`.`Horario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `futbolito`.`Horario` ;

CREATE TABLE IF NOT EXISTS `futbolito`.`Horario` (
  `idHorario` INT NOT NULL AUTO_INCREMENT,
  `Precio` INT NULL,
  `Dia` VARCHAR(45) NULL,
  `horaInicio` TIME NULL,
  `horaFin` TIME NULL,
  `idRecinto` INT NOT NULL,
  PRIMARY KEY (`idHorario`, `idRecinto`),
  INDEX `fk_Horario_Recinto1_idx` (`idRecinto` ASC),
  CONSTRAINT `fk_Horario_Recinto1`
    FOREIGN KEY (`idRecinto`)
    REFERENCES `futbolito`.`Recinto` (`idRecinto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futbolito`.`Torneo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `futbolito`.`Torneo` ;

CREATE TABLE IF NOT EXISTS `futbolito`.`Torneo` (
  `idTorneo` INT NOT NULL AUTO_INCREMENT,
  `FechaInicio` DATE NULL,
  `numeroParticipantes` INT NULL,
  `idCampeon` INT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idTorneo`),
  INDEX `fk_Torneo_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Torneo_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `futbolito`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futbolito`.`Equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `futbolito`.`Equipo` ;

CREATE TABLE IF NOT EXISTS `futbolito`.`Equipo` (
  `idEquipo` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `numeroPartidos` INT NULL,
  `numeroJugadores` VARCHAR(45) NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idEquipo`, `idUsuario`),
  INDEX `fk_Equipo_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Equipo_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `futbolito`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futbolito`.`Partido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `futbolito`.`Partido` ;

CREATE TABLE IF NOT EXISTS `futbolito`.`Partido` (
  `idPartido` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NULL,
  `horaInicio` TIME NULL,
  `horaFin` TIME NULL,
  `Estado` VARCHAR(45) NULL,
  `golesEquipo1` INT NULL,
  `golesEquipo2` INT NULL,
  `idEquipo1` INT NOT NULL,
  `idEquipo2` INT NOT NULL,
  `idCancha` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idPartido`),
  INDEX `fk_Partido_Equipo1_idx` (`idEquipo1` ASC),
  INDEX `fk_Partido_Equipo2_idx` (`idEquipo2` ASC),
  INDEX `fk_Partido_Cancha1_idx` (`idCancha` ASC),
  INDEX `fk_Partido_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Partido_Equipo1`
    FOREIGN KEY (`idEquipo1`)
    REFERENCES `futbolito`.`Equipo` (`idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partido_Equipo2`
    FOREIGN KEY (`idEquipo2`)
    REFERENCES `futbolito`.`Equipo` (`idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partido_Cancha1`
    FOREIGN KEY (`idCancha`)
    REFERENCES `futbolito`.`Cancha` (`idCancha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partido_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `futbolito`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futbolito`.`Competir`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `futbolito`.`Competir` ;

CREATE TABLE IF NOT EXISTS `futbolito`.`Competir` (
  `idTorneo` INT NOT NULL,
  `idEquipo` INT NOT NULL,
  PRIMARY KEY (`idTorneo`, `idEquipo`),
  INDEX `fk_Torneo_has_Equipo_Equipo1_idx` (`idEquipo` ASC),
  INDEX `fk_Torneo_has_Equipo_Torneo1_idx` (`idTorneo` ASC),
  CONSTRAINT `fk_Torneo_has_Equipo_Torneo1`
    FOREIGN KEY (`idTorneo`)
    REFERENCES `futbolito`.`Torneo` (`idTorneo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Torneo_has_Equipo_Equipo1`
    FOREIGN KEY (`idEquipo`)
    REFERENCES `futbolito`.`Equipo` (`idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futbolito`.`Jugador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `futbolito`.`Jugador` ;

CREATE TABLE IF NOT EXISTS `futbolito`.`Jugador` (
  `idJugador` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `idEquipo` INT NOT NULL,
  PRIMARY KEY (`idJugador`),
  INDEX `fk_Jugador_Equipo1_idx` (`idEquipo` ASC),
  CONSTRAINT `fk_Jugador_Equipo1`
    FOREIGN KEY (`idEquipo`)
    REFERENCES `futbolito`.`Equipo` (`idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
